### ISSUE TITLE
3rd party controls (SkiaSharp.Extended.UI.Controls.SKLottieView)

### ISSUE THREAD

**Issue by ankjin** [adospace/reactorui-maui#12]
Hi Ado,
I was trying to implement a SkiaSharp for lottie animation base on Gerard [youtube video](https://www.youtube.com/watch?v=o5X5yXdWpuc) and follow the MauiReactor 3rd party controls documentation. Could you please check what was wrong? Thank you
here's the link on my [github repo](https://github.com/ankjin/MauiReactorTestUI/blob/master/Pages/LottieAnimationPage.cs)

![image](https://user-images.githubusercontent.com/99092971/205480352-d50daa11-83d2-46ec-805a-782911f51428.png)

**Comment by adospace** [comment]
Hi,
I see a  couple of things:
1) You need to import the parents of the SKLottieView up to a standard control known by MauiReactor
2) From SKLottieView docs, I see you should set the Source property (not passing it to the constructor)

```c#
[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKSurfaceView))]
partial class SKSurfaceView { }

[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKAnimatedSurfaceView))]
partial class SKAnimatedSurfaceView { }

[Scaffold(typeof(SkiaSharp.Extended.UI.Controls.SKLottieView))]
partial class SKLottieView { }

class LottieAnimationPage : Component
{
    public override VisualNode Render()
    {
        return new ContentPage
        {
            new ScrollView
            {
                new VerticalStackLayout
                {
                    new SKLottieView()
                        .Source(new SKFileLottieImageSource
                        {
                            File = "dotnetbot.json"
                        })
                        .RepeatCount(1)
                        .HeightRequest(100)
                        .WidthRequest(100)
                        .HCenter()
                }
                .VCenter()
                .Spacing(25)
                .Padding(30, 0)
            }
        };
    }
}

```

you also may receive a warning like this:
![image](https://user-images.githubusercontent.com/10573253/205488278-5c4dea61-5235-4964-b876-27f53968fc27.png)
not consider it, will be fixed in coming release of the Scaffold library

**Comment by ankjin** [comment]
Although, I was able to run and display the dotnet bot inside skia controls using your code however it is not moving/animating. I hope it will be fix in coming release. Thank you

**Comment by adospace** [comment]
Hum, I'm not sure how SKLottieView works, is it functioning in a standard Maui application? The animation should start automatically?

**Comment by ankjin** [comment]
Yes, it is running fine in a standard Maui [(xaml)](https://github.com/ankjin/Mauivvm/blob/master/MauiApp1/View/BotAnimationPage.xaml) and even in a Maui [(markup)](https://github.com/ankjin/Mauivvm/blob/master/MauiApp1/View/BotAnimationMuPage.cs) application. But for MauiReactor (mvu) animation did not start automatically. If someone had across and had work around on this, please let us know so I can update my [repo](https://github.com/ankjin/MauiReactorTestUI/blob/master/Pages/LottieAnimationPage.cs) and for the benefit of others too.

**Comment by adospace** [comment]
ok, I got a look at the [[SKLottieView code](https://github.com/mono/SkiaSharp.Extended/blob/f205dd6201a0f08749308bd72fe0adbbdc7f4c05/source/SkiaSharp.Extended.UI/Controls/SKAnimatedSurfaceView.shared.cs#L5)] and seems quite strange to me the IsAnimationEnabled property implementation because the default value is false but then is set to true inside the SKAnimatedSurveyView constructor).

Long story short if you explicitly set IAnimationEnabled to true in MauiReactor it starts playing:
```c#
new SKLottieView()
    .Source(new SkiaSharp.Extended.UI.Controls.SKFileLottieImageSource()
    {
        File = "dotnetbot.json"
    })
    .IsAnimationEnabled(true)
    .RepeatCount(-1)
    .HeightRequest(200)
    .WidthRequest(200)
    .HCenter()
```

**Comment by ankjin** [comment]
You're right, setting up **IsAnimationEnabled** to **True** fixed the animation.
