### ISSUE TITLE
Support for Dependency Injection with Shell Routing Navigation

### ISSUE THREAD

**Issue by awasilik** [adospace/reactorui-maui#163]
Hello,

I recently started using this framework and I love how fluent it is.
I found the problem with Routing navigation though. I think it would be beneficial if Page I want to GoTo could be resolved from DependencyInjection rather than forcing it to have parameterless constructor.

<img width="984" alt="image" src="https://github.com/adospace/reactorui-maui/assets/33750371/4e530ef5-97a4-4296-ab63-1a7c65d5cae8">

<img width="1229" alt="image" src="https://github.com/adospace/reactorui-maui/assets/33750371/b877df7b-1706-44fc-838d-b42d1b25357c">

**Why is that beneficial?**

In current implementation I need to be responsible for controlling objects lifecycle and Container can not do that for me cause of using Service Location pattern.

**Comment by adospace** [comment]
Hi, yes that was something I thought initially when designing the library, I've also discussed it in other threads. 

Currently, you have to do something like this:

```csharp
public class SamplePage : Component<..>
{
  public override VisualNode Render()
  {
       var service = Services.GetRequiredService<ISampleService>();
       ....
  }
}

```

Even if I recognize that it could be cool to inject the service into the constructor, there could be some problems I need to address before allowing that.

1) Component MUST be transient, you can't just reuse a component (scoped/singleton)
2) Testing a component would mean setting up a DI container
3) Components could be really numerous (are not like views or viewmodels), in my applications, I have 50, 60, or more components. Forcing to use the DI would mean registering components at startup or worse scanning the assemblies.

We could of course solve them in some way but I couldn't find so far the cleanest way: the main reason I guess is that Components are "not" Services (neither Views nor ViewModels in MVVM are services too IMO).

I'm open to suggestions, maybe it's something doable for the .NET 8 porting time frame

**Comment by adospace** [comment]
4) not sure what to do if you create a component on the fly when hot-reloading

**Comment by awasilik** [comment]
Thanks for quick answer!
I understand reasoning, I think building container with 50-60 components shouldn't take significant time (something to check probably).
For now it's not a big problem, but injecting a service that's disposable forces me to clean it up in OnWillUnmount.
Having that in mind, it's not always obvious I can do that (what if it's singleton or will be changed to singleton). Having container create those services allows container to clean up after them.

**Comment by adospace** [comment]
I understand your reason, but, actually, your use case is another reason to not directly inject a disposable service.
Disposable services are hard to manage out of a scope. 
In ASP.NET applications you have the scope linked to the request, so it's pretty easy to inject something like a DbContext that is disposable and registered as Scoped.

In a UI application like this, there isn't a scope automatically created (excluding the main scope that is closed at the shutdown of the application) because there isn't the concept of a request or something like that (like it happens in Blazor).

So in general, Components shouldn't be disposable because they would be registered as transient.
If you inject a scoped service directly you could get an exception as there isn't a scope.
If you want to use a disposed service just create a scope and dispose of it asap:

```csharp
public override VisualNode Render()
{
  using IServiceScope serviceScope = services.CreateScope();
  var disposableService = serviceScope.ServiceProvider.GetRequiredService<IMyDisposableService>();
  ....
}
```

of course feel free to for the repository and experiment with it

**Comment by awasilik** [comment]
I rather meant that Component is using a Transient disposable service. Nevertheless I understand the reasoning and that's not something I can't overcome in the app, I just find it a bit restricting.

I'll fork and if I can think of something I can present the results. 
Thank you for quick responses! Feel free to close the issue :)
