### ISSUE TITLE
Does this support ObservableCollection for CollectionView?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [adospace/reactorui-maui#18]
Is it possible to use ObservableCollection for CollectionView so that items can be added or removed without changing the whole collection? If it is possible then how?

**Comment by adospace** [comment]
Well, usually in an MVU approach you shouldn't bind the ItemsSource property to an ObservableCollection: MauiReactor caches native controls used to render the single items so that it should be pretty fast even for large lists.

Do you have any sample code to share any issue you have with that approach?

**Comment by ziaulhasanhamim** [comment]
No, I don't have any issues with that. I just thought it would be a waste of CPU cycles to re-allocate an array every time you want to add something
