### ISSUE TITLE
Reactor.Maui.TemplatePack

### ISSUE THREAD

**Issue by roughiain** [adospace/reactorui-maui#23]
The build property on `dotnet_bot.svg` is not set to `MauiImage` causing the image not to be displayed.

```
Reactor.Maui.TemplatePack
      Version: 1.0.103
      Details:
         Author: adospace
         NuGetSource: https://api.nuget.org/v3/index.json
      Templates:
         MauiReactor based app (maui-reactor-startup) C#
      Uninstall Command:
         dotnet new uninstall Reactor.Maui.TemplatePack
```

Thanks for the awesome work on this.

**Comment by adospace** [comment]
Hi, thanks for reporting it, actually seems correct to me:
![image](https://user-images.githubusercontent.com/10573253/216368288-3b157fc9-664b-461d-84f7-26b08a06f5ec.png)

do you see the issue in the created project?

**Comment by roughiain** [comment]
Yes, had to manually update the properties in Visual studio

```
dotnet new maui-reactor-startup -o maui-reactor-playground1
The template "MauiReactor based app" was created successfully.
```

![image](https://user-images.githubusercontent.com/19661735/216539380-794d284d-43e8-4e81-ab03-ee849e90f9d3.png)

**Comment by adospace** [comment]
hum, I guess there is something going on with the IDE you're using (VS mac 2022?), this is vs under windows:
![image](https://user-images.githubusercontent.com/10573253/216570200-6c3ce7f0-6636-4574-ac62-01bf7e48cddb.png)

also as you can see in row 33 you have the <MauiImage... for the folder Resources\Images\*> so that everything inside Images should be considered MauiImage.

**Comment by roughiain** [comment]
VSMac strikes again :(
