### ISSUE TITLE
iOS NavigationPage OnWillUnmount not called

### ISSUE THREAD

**Issue by mario-zelger** [adospace/reactorui-maui#251]
It seems that on iOS `OnWillUnmount` is not called when popping a page from the navigation stack when using a `NavigationPage`. It does work as expected on Android (tested with API 32). Might be related to or a regression from #164. 

**To Reproduce**
I'm currently using the following setup for which I can reproduce the behavior with the sample code.

* .NET 8.0.8
* Microsoft.Maui.Controls 8.0.80
* Reactor.Maui 2.0.46

```csharp
class MainPage : Component
{
    public override VisualNode Render() => NavigationPage(new HomePage());
}

class HomePage : Component
{
    public override VisualNode Render()
        => ContentPage(
            ScrollView(
                VStack(
                        Button("GoTo SubPage")
                            .OnClicked(() => Navigation.PushAsync<SubPage>())
                    )
                    .VCenter()
                    .Spacing(25)
                    .Padding(30, 0)
            )
        );
}

class SubPage : Component
{
    protected override void OnMounted()
    {
        // This is "correctly" called every time the page is pushed to the navigation stack.
        // Without ever calling OnWillUnmount this could lead to memory leaks though.
        Console.WriteLine("SubPage.OnMounted");
        base.OnMounted();
    }

    protected override void OnWillUnmount()
    {
        // This is never called. Either via Back-Button or via PopAsync
        Console.WriteLine("SubPage.OnWillUnmount");
        base.OnWillUnmount();
    }

    public override VisualNode Render()
        => ContentPage(
            VStack(
                    Label("SubPage"),
                    Button("GoBack")
                        .OnClicked(() => Navigation.PopAsync())
                )
                .Spacing(16)
                .VCenter()
        );
}
```

**Expected behavior**
I'd expect that `OnWillUnmount` for `SubPage` is called as soon as I navigate back to the `HomePage`.

**Smartphone:**
- iPhone 15 Pro, iOS 17.5 (Simluator)
- iPhone 12 Pro Max, iOS 17.6.1 (physical Device)

**Comment by adospace** [comment]
Hi, the problem seems related to the strange behavior of the events Appearing/Disappearing in iOS.

Android:
When you move back to the previous page (Navigation.PopAsync()) the event Disappearing is raised AND NavigationStack doesn't contain anymore the page.
When you move to the next page (Navigation.PushAsync()) the event Disappearing is raised AND NavigationStack still contains the page.

IOS:
When you move back to the previous page (Navigation.PopAsync()) the event Disappearing is raised **BUT** NavigationStack still contains the page.
When you move to the next page (Navigation.PushAsync()) the event Disappearing is raised AND NavigationStack still contains the page as happened for the case when you move back.

So MauiReactor under iOS can't know if it can OnMount the component or not, and following the Android behavior it doesn't right now causing possible memory leaks.

This is a serious bug thanks for reporting it, still investigating.
