### ISSUE TITLE
Android 9: Button not working after app resume from background

### ISSUE THREAD

**Issue by coolyuwk** [adospace/reactorui-maui#26]
https://user-images.githubusercontent.com/6112111/218619802-5bcb7d6e-60b4-4f13-9080-9550bfc6f3db.mp4

**Comment by adospace** [comment]
are you on the latest version?

**Comment by coolyuwk** [comment]
@adospace 
![image](https://user-images.githubusercontent.com/6112111/218972418-1c3e8e2d-4e7c-47bd-891a-4c0f4929da54.png)

**Comment by adospace** [comment]
Tested with the Emulator Android 9.0 API 28 and version 104 seems working fine.
Anyway, it's clear that in it doesn't: the app is not receiving the resume event so that MauiReactor loop remains paused.
I think I fixed the issue by removing the suspension code in version 105.
Please update the MauiReactor version to latest and kindly report if it fixes your scenario, thanks

**Comment by coolyuwk** [comment]
Version 105 works fine, thanks.
